%% Generate Sensor Readings through Derby model
 % ---------------------------------------------------------------------
 % This function allows the computation of the 3D field coordinates of the
 % magnetic flux density of an axially symmetric solenoid (or equivalently
 % of an axially magnetized permanent magnet) for the whole sensor array.
 %
 % The function calls "WrapBfield3.m", that is, the function computing the
 % radial and axial coordinates of the field with respect to a local 
 % reference frame centered on the center of the solenoid (magnet).
 % Please refer to Derby 2009 for the detailed derivation of the model.
 %
 % Inputs:
 %    1) D      : diameter of the magnet                          [MMx1]
 %    2) L      : length of the magnet                            [MMx1] 
 %    3) M      : magnetization of the magnet                     [MMx1]
 %    4) MagPos : the first three elements are the cartesian coordinates 
 %                of the center of the magnet, while the the latter three
 %                express the pose of the magnet, magnetic moment
 %                expressed as a unit vector                      [MMx6]
 %    5) SensorPositionMatrix  : cartesian coordinates of the points 
 %                feeling the field generated by the magnet     [Nsensx3]
 %
 % Output:
 %    1) Readings   : x-component of the magnetic field         [Nsens*3]
 %  
 % ATTENTION: the code consider every input vector as a column vector!
 % ---------------------------------------------------------------------
 % September 10th, 2019                         Author: Federico Masiero
 % ---------------------------------------------------------------------


function Readings = GenerateReadings(MagnetPoses,SensorPositionMatrix,...
                                      M,D,L)

Nsens    = size(SensorPositionMatrix,1); 
MM       = size(MagnetPoses,1);
Readings = zeros(Nsens,3);

for u = 1:MM
    for i = 1:Nsens
        Point = SensorPositionMatrix(i,:)';
        [Bx, By, Bz] = WrapCylBfield3(D(u),L(u),M(u),MagnetPoses(u,:)',Point);
        Readings(i,:) = Readings(i,:) + [Bx By Bz];
    end
end

% Fix resolution to milligauss
Readings = fix(Readings*1e7)*(1e-7);
